# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Erik J. Murray
email: erikjmurray@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Erik J Murray's professional website.
  A broadcast engineer dabbling in software development.
  Links to socials, email, and resume.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://erikjmurray.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_handle: erikjmurray
github_username:  erikjmurray
permalink: /:categories/:title



# Build settings
theme: null
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: "" 
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts" 
    values:
      layout: "blog-post"       # overrides previous default layout
      author: "Erik Murray"
      page-num: 0
      last: false

# Prevent h1 from rendering in TOC
kramdown:
  toc_levels: 2..6

# Collections
collections_dir: collections

collections:
  other:
    output: true
  something:
    output: true